// Code generated by protoc-gen-go. DO NOT EDIT.
// source: machine.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Port struct {
	Port                 uint32   `protobuf:"varint,1,opt,name=port,proto3" json:"port,omitempty"`
	Service              string   `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Port) Reset()         { *m = Port{} }
func (m *Port) String() string { return proto.CompactTextString(m) }
func (*Port) ProtoMessage()    {}
func (*Port) Descriptor() ([]byte, []int) {
	return fileDescriptor_machine_91d82d900b0a1774, []int{0}
}
func (m *Port) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Port.Unmarshal(m, b)
}
func (m *Port) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Port.Marshal(b, m, deterministic)
}
func (dst *Port) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Port.Merge(dst, src)
}
func (m *Port) XXX_Size() int {
	return xxx_messageInfo_Port.Size(m)
}
func (m *Port) XXX_DiscardUnknown() {
	xxx_messageInfo_Port.DiscardUnknown(m)
}

var xxx_messageInfo_Port proto.InternalMessageInfo

func (m *Port) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *Port) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

type Address struct {
	Ip                   string   `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Ports                []*Port  `protobuf:"bytes,2,rep,name=ports,proto3" json:"ports,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Address) Reset()         { *m = Address{} }
func (m *Address) String() string { return proto.CompactTextString(m) }
func (*Address) ProtoMessage()    {}
func (*Address) Descriptor() ([]byte, []int) {
	return fileDescriptor_machine_91d82d900b0a1774, []int{1}
}
func (m *Address) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Address.Unmarshal(m, b)
}
func (m *Address) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Address.Marshal(b, m, deterministic)
}
func (dst *Address) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Address.Merge(dst, src)
}
func (m *Address) XXX_Size() int {
	return xxx_messageInfo_Address.Size(m)
}
func (m *Address) XXX_DiscardUnknown() {
	xxx_messageInfo_Address.DiscardUnknown(m)
}

var xxx_messageInfo_Address proto.InternalMessageInfo

func (m *Address) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *Address) GetPorts() []*Port {
	if m != nil {
		return m.Ports
	}
	return nil
}

type Iface struct {
	Name                 string     `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Address              []*Address `protobuf:"bytes,2,rep,name=address,proto3" json:"address,omitempty"`
	Error                string     `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Iface) Reset()         { *m = Iface{} }
func (m *Iface) String() string { return proto.CompactTextString(m) }
func (*Iface) ProtoMessage()    {}
func (*Iface) Descriptor() ([]byte, []int) {
	return fileDescriptor_machine_91d82d900b0a1774, []int{2}
}
func (m *Iface) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Iface.Unmarshal(m, b)
}
func (m *Iface) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Iface.Marshal(b, m, deterministic)
}
func (dst *Iface) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Iface.Merge(dst, src)
}
func (m *Iface) XXX_Size() int {
	return xxx_messageInfo_Iface.Size(m)
}
func (m *Iface) XXX_DiscardUnknown() {
	xxx_messageInfo_Iface.DiscardUnknown(m)
}

var xxx_messageInfo_Iface proto.InternalMessageInfo

func (m *Iface) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Iface) GetAddress() []*Address {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *Iface) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type Machine struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Ifaces               []*Iface `protobuf:"bytes,2,rep,name=ifaces,proto3" json:"ifaces,omitempty"`
	Error                string   `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Machine) Reset()         { *m = Machine{} }
func (m *Machine) String() string { return proto.CompactTextString(m) }
func (*Machine) ProtoMessage()    {}
func (*Machine) Descriptor() ([]byte, []int) {
	return fileDescriptor_machine_91d82d900b0a1774, []int{3}
}
func (m *Machine) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Machine.Unmarshal(m, b)
}
func (m *Machine) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Machine.Marshal(b, m, deterministic)
}
func (dst *Machine) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Machine.Merge(dst, src)
}
func (m *Machine) XXX_Size() int {
	return xxx_messageInfo_Machine.Size(m)
}
func (m *Machine) XXX_DiscardUnknown() {
	xxx_messageInfo_Machine.DiscardUnknown(m)
}

var xxx_messageInfo_Machine proto.InternalMessageInfo

func (m *Machine) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *Machine) GetIfaces() []*Iface {
	if m != nil {
		return m.Ifaces
	}
	return nil
}

func (m *Machine) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*Port)(nil), "pb.Port")
	proto.RegisterType((*Address)(nil), "pb.Address")
	proto.RegisterType((*Iface)(nil), "pb.Iface")
	proto.RegisterType((*Machine)(nil), "pb.Machine")
}

func init() { proto.RegisterFile("machine.proto", fileDescriptor_machine_91d82d900b0a1774) }

var fileDescriptor_machine_91d82d900b0a1774 = []byte{
	// 221 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xbf, 0x4f, 0xc3, 0x30,
	0x10, 0x85, 0x15, 0xb7, 0x69, 0xc8, 0x55, 0x65, 0x38, 0x31, 0x78, 0x42, 0x21, 0x12, 0x52, 0xa6,
	0x0c, 0xc0, 0xc2, 0xc8, 0xc8, 0x80, 0x84, 0x3c, 0x20, 0x56, 0x27, 0x31, 0xc2, 0x43, 0x6b, 0xeb,
	0x9c, 0xf0, 0xf7, 0xa3, 0xf3, 0x8f, 0xad, 0xdb, 0x3b, 0x9f, 0xbe, 0xef, 0xd9, 0x86, 0xd3, 0x59,
	0xcf, 0xbf, 0xf6, 0x62, 0x46, 0x4f, 0x6e, 0x75, 0x28, 0xfc, 0xd4, 0xbf, 0xc0, 0xfe, 0xd3, 0xd1,
	0x8a, 0x08, 0x7b, 0xef, 0x68, 0x95, 0x55, 0x57, 0x0d, 0x27, 0x15, 0x33, 0x4a, 0x68, 0x82, 0xa1,
	0x3f, 0x3b, 0x1b, 0x29, 0xba, 0x6a, 0x68, 0x55, 0x19, 0xfb, 0x57, 0x68, 0xde, 0x96, 0x85, 0x4c,
	0x08, 0x78, 0x0b, 0xc2, 0xfa, 0x88, 0xb5, 0x4a, 0x58, 0x8f, 0xf7, 0x50, 0x33, 0x1c, 0xa4, 0xe8,
	0x76, 0xc3, 0xf1, 0xe9, 0x66, 0xf4, 0xd3, 0xc8, 0x0d, 0x2a, 0x1d, 0xf7, 0xdf, 0x50, 0xbf, 0xff,
	0xe8, 0xd9, 0x70, 0xe3, 0x45, 0x9f, 0x4d, 0x46, 0x63, 0xc6, 0x47, 0x68, 0x74, 0xf2, 0x66, 0xfc,
	0xc8, 0x78, 0xae, 0x52, 0x65, 0x87, 0x77, 0x50, 0x1b, 0x22, 0x47, 0x72, 0x17, 0xd9, 0x34, 0xf4,
	0x5f, 0xd0, 0x7c, 0xa4, 0xf7, 0xb1, 0x7b, 0xdb, 0xec, 0x52, 0xdc, 0x9c, 0xf1, 0x01, 0x0e, 0x96,
	0x8b, 0x8b, 0xba, 0x65, 0x75, 0xbc, 0x8a, 0xca, 0x8b, 0xeb, 0xde, 0xe9, 0x10, 0x7f, 0xeb, 0xf9,
	0x3f, 0x00, 0x00, 0xff, 0xff, 0x65, 0xb8, 0x22, 0x2a, 0x3e, 0x01, 0x00, 0x00,
}
