// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Machine.proto

package machine

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Port struct {
	Port                 uint32   `protobuf:"varint,1,opt,name=port,proto3" json:"port,omitempty"`
	Service              string   `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Port) Reset()         { *m = Port{} }
func (m *Port) String() string { return proto.CompactTextString(m) }
func (*Port) ProtoMessage()    {}
func (*Port) Descriptor() ([]byte, []int) {
	return fileDescriptor_49547078e0f55cfe, []int{0}
}

func (m *Port) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Port.Unmarshal(m, b)
}
func (m *Port) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Port.Marshal(b, m, deterministic)
}
func (m *Port) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Port.Merge(m, src)
}
func (m *Port) XXX_Size() int {
	return xxx_messageInfo_Port.Size(m)
}
func (m *Port) XXX_DiscardUnknown() {
	xxx_messageInfo_Port.DiscardUnknown(m)
}

var xxx_messageInfo_Port proto.InternalMessageInfo

func (m *Port) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *Port) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

type Address struct {
	Ip                   string   `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Ports                []*Port  `protobuf:"bytes,2,rep,name=ports,proto3" json:"ports,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Address) Reset()         { *m = Address{} }
func (m *Address) String() string { return proto.CompactTextString(m) }
func (*Address) ProtoMessage()    {}
func (*Address) Descriptor() ([]byte, []int) {
	return fileDescriptor_49547078e0f55cfe, []int{1}
}

func (m *Address) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Address.Unmarshal(m, b)
}
func (m *Address) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Address.Marshal(b, m, deterministic)
}
func (m *Address) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Address.Merge(m, src)
}
func (m *Address) XXX_Size() int {
	return xxx_messageInfo_Address.Size(m)
}
func (m *Address) XXX_DiscardUnknown() {
	xxx_messageInfo_Address.DiscardUnknown(m)
}

var xxx_messageInfo_Address proto.InternalMessageInfo

func (m *Address) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *Address) GetPorts() []*Port {
	if m != nil {
		return m.Ports
	}
	return nil
}

type Iface struct {
	Name                 string     `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Address              []*Address `protobuf:"bytes,2,rep,name=address,proto3" json:"address,omitempty"`
	Error                string     `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Iface) Reset()         { *m = Iface{} }
func (m *Iface) String() string { return proto.CompactTextString(m) }
func (*Iface) ProtoMessage()    {}
func (*Iface) Descriptor() ([]byte, []int) {
	return fileDescriptor_49547078e0f55cfe, []int{2}
}

func (m *Iface) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Iface.Unmarshal(m, b)
}
func (m *Iface) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Iface.Marshal(b, m, deterministic)
}
func (m *Iface) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Iface.Merge(m, src)
}
func (m *Iface) XXX_Size() int {
	return xxx_messageInfo_Iface.Size(m)
}
func (m *Iface) XXX_DiscardUnknown() {
	xxx_messageInfo_Iface.DiscardUnknown(m)
}

var xxx_messageInfo_Iface proto.InternalMessageInfo

func (m *Iface) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Iface) GetAddress() []*Address {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *Iface) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type Machine struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Ifaces               []*Iface `protobuf:"bytes,2,rep,name=ifaces,proto3" json:"ifaces,omitempty"`
	Error                string   `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Machine) Reset()         { *m = Machine{} }
func (m *Machine) String() string { return proto.CompactTextString(m) }
func (*Machine) ProtoMessage()    {}
func (*Machine) Descriptor() ([]byte, []int) {
	return fileDescriptor_49547078e0f55cfe, []int{3}
}

func (m *Machine) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Machine.Unmarshal(m, b)
}
func (m *Machine) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Machine.Marshal(b, m, deterministic)
}
func (m *Machine) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Machine.Merge(m, src)
}
func (m *Machine) XXX_Size() int {
	return xxx_messageInfo_Machine.Size(m)
}
func (m *Machine) XXX_DiscardUnknown() {
	xxx_messageInfo_Machine.DiscardUnknown(m)
}

var xxx_messageInfo_Machine proto.InternalMessageInfo

func (m *Machine) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *Machine) GetIfaces() []*Iface {
	if m != nil {
		return m.Ifaces
	}
	return nil
}

func (m *Machine) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type SaveRequest struct {
	Machine              *Machine `protobuf:"bytes,1,opt,name=machine,proto3" json:"machine,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SaveRequest) Reset()         { *m = SaveRequest{} }
func (m *SaveRequest) String() string { return proto.CompactTextString(m) }
func (*SaveRequest) ProtoMessage()    {}
func (*SaveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_49547078e0f55cfe, []int{4}
}

func (m *SaveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveRequest.Unmarshal(m, b)
}
func (m *SaveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveRequest.Marshal(b, m, deterministic)
}
func (m *SaveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveRequest.Merge(m, src)
}
func (m *SaveRequest) XXX_Size() int {
	return xxx_messageInfo_SaveRequest.Size(m)
}
func (m *SaveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SaveRequest proto.InternalMessageInfo

func (m *SaveRequest) GetMachine() *Machine {
	if m != nil {
		return m.Machine
	}
	return nil
}

type SaveReply struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SaveReply) Reset()         { *m = SaveReply{} }
func (m *SaveReply) String() string { return proto.CompactTextString(m) }
func (*SaveReply) ProtoMessage()    {}
func (*SaveReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_49547078e0f55cfe, []int{5}
}

func (m *SaveReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveReply.Unmarshal(m, b)
}
func (m *SaveReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveReply.Marshal(b, m, deterministic)
}
func (m *SaveReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveReply.Merge(m, src)
}
func (m *SaveReply) XXX_Size() int {
	return xxx_messageInfo_SaveReply.Size(m)
}
func (m *SaveReply) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveReply.DiscardUnknown(m)
}

var xxx_messageInfo_SaveReply proto.InternalMessageInfo

func (m *SaveReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*Port)(nil), "machine.Port")
	proto.RegisterType((*Address)(nil), "machine.Address")
	proto.RegisterType((*Iface)(nil), "machine.Iface")
	proto.RegisterType((*Machine)(nil), "machine.Machine")
	proto.RegisterType((*SaveRequest)(nil), "machine.SaveRequest")
	proto.RegisterType((*SaveReply)(nil), "machine.SaveReply")
}

func init() { proto.RegisterFile("Machine.proto", fileDescriptor_49547078e0f55cfe) }

var fileDescriptor_49547078e0f55cfe = []byte{
	// 292 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0xc1, 0x4b, 0xc3, 0x30,
	0x14, 0xc6, 0x6d, 0xb7, 0xae, 0xf4, 0xcd, 0x0e, 0x79, 0xec, 0x50, 0x3c, 0x95, 0x8a, 0x52, 0x3c,
	0xf4, 0x30, 0xbd, 0x78, 0x11, 0x3c, 0xee, 0x20, 0x48, 0x3c, 0x8a, 0x87, 0xd8, 0x3e, 0x35, 0xb0,
	0xae, 0x31, 0x69, 0x07, 0xfb, 0xef, 0x25, 0x69, 0x52, 0x86, 0xe0, 0xed, 0x7d, 0x4d, 0xbe, 0xef,
	0xf7, 0xbd, 0x14, 0xd2, 0x67, 0x5e, 0x7f, 0x8b, 0x3d, 0x55, 0x52, 0x75, 0x7d, 0x87, 0x71, 0x3b,
	0xca, 0xe2, 0x1e, 0xe6, 0x2f, 0x9d, 0xea, 0x11, 0x61, 0x2e, 0x3b, 0xd5, 0x67, 0x41, 0x1e, 0x94,
	0x29, 0xb3, 0x33, 0x66, 0x10, 0x6b, 0x52, 0x07, 0x51, 0x53, 0x16, 0xe6, 0x41, 0x99, 0x30, 0x2f,
	0x8b, 0x47, 0x88, 0x9f, 0x9a, 0x46, 0x91, 0xd6, 0xb8, 0x82, 0x50, 0x48, 0x6b, 0x4b, 0x58, 0x28,
	0x24, 0x5e, 0x41, 0x64, 0xcc, 0x3a, 0x0b, 0xf3, 0x59, 0xb9, 0xdc, 0xa4, 0x95, 0x23, 0x55, 0x06,
	0xc3, 0xc6, 0xb3, 0xe2, 0x1d, 0xa2, 0xed, 0x27, 0xaf, 0xc9, 0x60, 0xf7, 0xbc, 0x25, 0xe7, 0xb7,
	0x33, 0xde, 0x42, 0xcc, 0xc7, 0x70, 0x97, 0x71, 0x31, 0x65, 0x38, 0x28, 0xf3, 0x17, 0x70, 0x0d,
	0x11, 0x29, 0xd5, 0xa9, 0x6c, 0x66, 0x03, 0x46, 0x51, 0xbc, 0x41, 0xec, 0xd6, 0x35, 0x80, 0x61,
	0x10, 0x8d, 0x07, 0x98, 0x19, 0x6f, 0x60, 0x21, 0x0c, 0xdd, 0xe7, 0xaf, 0xa6, 0x7c, 0x5b, 0x8a,
	0xb9, 0xd3, 0x7f, 0xc2, 0x1f, 0x60, 0xf9, 0xca, 0x0f, 0xc4, 0xe8, 0x67, 0x20, 0xdd, 0x9b, 0xb6,
	0xce, 0x6d, 0x19, 0xa7, 0x6d, 0x5d, 0x07, 0x36, 0x3d, 0xf6, 0x35, 0x24, 0xa3, 0x55, 0xee, 0x8e,
	0xe6, 0x75, 0x5b, 0xd2, 0x9a, 0x7f, 0xf9, 0xed, 0xbd, 0xdc, 0x6c, 0xe1, 0xdc, 0x59, 0xcd, 0x6d,
	0x85, 0x8e, 0xe8, 0x57, 0x5a, 0x4f, 0x80, 0x93, 0x1e, 0x97, 0xf8, 0xe7, 0xab, 0xdc, 0x1d, 0x8b,
	0xb3, 0x8f, 0x85, 0xfd, 0xdd, 0x77, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x30, 0x07, 0xe9, 0x63,
	0xff, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MachineSaverClient is the client API for MachineSaver service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MachineSaverClient interface {
	SaveMachine(ctx context.Context, in *SaveRequest, opts ...grpc.CallOption) (*SaveReply, error)
}

type machineSaverClient struct {
	cc *grpc.ClientConn
}

func NewMachineSaverClient(cc *grpc.ClientConn) MachineSaverClient {
	return &machineSaverClient{cc}
}

func (c *machineSaverClient) SaveMachine(ctx context.Context, in *SaveRequest, opts ...grpc.CallOption) (*SaveReply, error) {
	out := new(SaveReply)
	err := c.cc.Invoke(ctx, "/machine.MachineSaver/SaveMachine", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MachineSaverServer is the server API for MachineSaver service.
type MachineSaverServer interface {
	SaveMachine(context.Context, *SaveRequest) (*SaveReply, error)
}

// UnimplementedMachineSaverServer can be embedded to have forward compatible implementations.
type UnimplementedMachineSaverServer struct {
}

func (*UnimplementedMachineSaverServer) SaveMachine(ctx context.Context, req *SaveRequest) (*SaveReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveMachine not implemented")
}

func RegisterMachineSaverServer(s *grpc.Server, srv MachineSaverServer) {
	s.RegisterService(&_MachineSaver_serviceDesc, srv)
}

func _MachineSaver_SaveMachine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MachineSaverServer).SaveMachine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/machine.MachineSaver/SaveMachine",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MachineSaverServer).SaveMachine(ctx, req.(*SaveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MachineSaver_serviceDesc = grpc.ServiceDesc{
	ServiceName: "machine.MachineSaver",
	HandlerType: (*MachineSaverServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SaveMachine",
			Handler:    _MachineSaver_SaveMachine_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "Machine.proto",
}
