// Code generated by protoc-gen-go. DO NOT EDIT.
// source: workerServer.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SaveMachineRes_RequestStatus int32

const (
	SaveMachineRes_UNKNOWN      SaveMachineRes_RequestStatus = 0
	SaveMachineRes_ACCEPTED     SaveMachineRes_RequestStatus = 1
	SaveMachineRes_NOT_ACCEPTED SaveMachineRes_RequestStatus = 2
)

var SaveMachineRes_RequestStatus_name = map[int32]string{
	0: "UNKNOWN",
	1: "ACCEPTED",
	2: "NOT_ACCEPTED",
}

var SaveMachineRes_RequestStatus_value = map[string]int32{
	"UNKNOWN":      0,
	"ACCEPTED":     1,
	"NOT_ACCEPTED": 2,
}

func (x SaveMachineRes_RequestStatus) String() string {
	return proto.EnumName(SaveMachineRes_RequestStatus_name, int32(x))
}

func (SaveMachineRes_RequestStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_918d5dbb74273f6d, []int{5, 0}
}

type Port struct {
	Port                 uint32   `protobuf:"varint,1,opt,name=port,proto3" json:"port,omitempty"`
	Service              string   `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Port) Reset()         { *m = Port{} }
func (m *Port) String() string { return proto.CompactTextString(m) }
func (*Port) ProtoMessage()    {}
func (*Port) Descriptor() ([]byte, []int) {
	return fileDescriptor_918d5dbb74273f6d, []int{0}
}

func (m *Port) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Port.Unmarshal(m, b)
}
func (m *Port) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Port.Marshal(b, m, deterministic)
}
func (m *Port) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Port.Merge(m, src)
}
func (m *Port) XXX_Size() int {
	return xxx_messageInfo_Port.Size(m)
}
func (m *Port) XXX_DiscardUnknown() {
	xxx_messageInfo_Port.DiscardUnknown(m)
}

var xxx_messageInfo_Port proto.InternalMessageInfo

func (m *Port) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *Port) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

type Address struct {
	Ip                   string   `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Ports                []*Port  `protobuf:"bytes,2,rep,name=ports,proto3" json:"ports,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Address) Reset()         { *m = Address{} }
func (m *Address) String() string { return proto.CompactTextString(m) }
func (*Address) ProtoMessage()    {}
func (*Address) Descriptor() ([]byte, []int) {
	return fileDescriptor_918d5dbb74273f6d, []int{1}
}

func (m *Address) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Address.Unmarshal(m, b)
}
func (m *Address) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Address.Marshal(b, m, deterministic)
}
func (m *Address) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Address.Merge(m, src)
}
func (m *Address) XXX_Size() int {
	return xxx_messageInfo_Address.Size(m)
}
func (m *Address) XXX_DiscardUnknown() {
	xxx_messageInfo_Address.DiscardUnknown(m)
}

var xxx_messageInfo_Address proto.InternalMessageInfo

func (m *Address) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *Address) GetPorts() []*Port {
	if m != nil {
		return m.Ports
	}
	return nil
}

type Iface struct {
	Name                 string     `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Address              []*Address `protobuf:"bytes,2,rep,name=address,proto3" json:"address,omitempty"`
	Error                string     `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Iface) Reset()         { *m = Iface{} }
func (m *Iface) String() string { return proto.CompactTextString(m) }
func (*Iface) ProtoMessage()    {}
func (*Iface) Descriptor() ([]byte, []int) {
	return fileDescriptor_918d5dbb74273f6d, []int{2}
}

func (m *Iface) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Iface.Unmarshal(m, b)
}
func (m *Iface) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Iface.Marshal(b, m, deterministic)
}
func (m *Iface) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Iface.Merge(m, src)
}
func (m *Iface) XXX_Size() int {
	return xxx_messageInfo_Iface.Size(m)
}
func (m *Iface) XXX_DiscardUnknown() {
	xxx_messageInfo_Iface.DiscardUnknown(m)
}

var xxx_messageInfo_Iface proto.InternalMessageInfo

func (m *Iface) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Iface) GetAddress() []*Address {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *Iface) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type Machine struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Ifaces               []*Iface `protobuf:"bytes,2,rep,name=ifaces,proto3" json:"ifaces,omitempty"`
	Error                string   `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Machine) Reset()         { *m = Machine{} }
func (m *Machine) String() string { return proto.CompactTextString(m) }
func (*Machine) ProtoMessage()    {}
func (*Machine) Descriptor() ([]byte, []int) {
	return fileDescriptor_918d5dbb74273f6d, []int{3}
}

func (m *Machine) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Machine.Unmarshal(m, b)
}
func (m *Machine) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Machine.Marshal(b, m, deterministic)
}
func (m *Machine) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Machine.Merge(m, src)
}
func (m *Machine) XXX_Size() int {
	return xxx_messageInfo_Machine.Size(m)
}
func (m *Machine) XXX_DiscardUnknown() {
	xxx_messageInfo_Machine.DiscardUnknown(m)
}

var xxx_messageInfo_Machine proto.InternalMessageInfo

func (m *Machine) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *Machine) GetIfaces() []*Iface {
	if m != nil {
		return m.Ifaces
	}
	return nil
}

func (m *Machine) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type SaveMachineReq struct {
	Machine              *Machine `protobuf:"bytes,1,opt,name=machine,proto3" json:"machine,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SaveMachineReq) Reset()         { *m = SaveMachineReq{} }
func (m *SaveMachineReq) String() string { return proto.CompactTextString(m) }
func (*SaveMachineReq) ProtoMessage()    {}
func (*SaveMachineReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_918d5dbb74273f6d, []int{4}
}

func (m *SaveMachineReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveMachineReq.Unmarshal(m, b)
}
func (m *SaveMachineReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveMachineReq.Marshal(b, m, deterministic)
}
func (m *SaveMachineReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveMachineReq.Merge(m, src)
}
func (m *SaveMachineReq) XXX_Size() int {
	return xxx_messageInfo_SaveMachineReq.Size(m)
}
func (m *SaveMachineReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveMachineReq.DiscardUnknown(m)
}

var xxx_messageInfo_SaveMachineReq proto.InternalMessageInfo

func (m *SaveMachineReq) GetMachine() *Machine {
	if m != nil {
		return m.Machine
	}
	return nil
}

type SaveMachineRes struct {
	Status               SaveMachineRes_RequestStatus `protobuf:"varint,1,opt,name=status,proto3,enum=pb.SaveMachineRes_RequestStatus" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *SaveMachineRes) Reset()         { *m = SaveMachineRes{} }
func (m *SaveMachineRes) String() string { return proto.CompactTextString(m) }
func (*SaveMachineRes) ProtoMessage()    {}
func (*SaveMachineRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_918d5dbb74273f6d, []int{5}
}

func (m *SaveMachineRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveMachineRes.Unmarshal(m, b)
}
func (m *SaveMachineRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveMachineRes.Marshal(b, m, deterministic)
}
func (m *SaveMachineRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveMachineRes.Merge(m, src)
}
func (m *SaveMachineRes) XXX_Size() int {
	return xxx_messageInfo_SaveMachineRes.Size(m)
}
func (m *SaveMachineRes) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveMachineRes.DiscardUnknown(m)
}

var xxx_messageInfo_SaveMachineRes proto.InternalMessageInfo

func (m *SaveMachineRes) GetStatus() SaveMachineRes_RequestStatus {
	if m != nil {
		return m.Status
	}
	return SaveMachineRes_UNKNOWN
}

func init() {
	proto.RegisterEnum("pb.SaveMachineRes_RequestStatus", SaveMachineRes_RequestStatus_name, SaveMachineRes_RequestStatus_value)
	proto.RegisterType((*Port)(nil), "pb.Port")
	proto.RegisterType((*Address)(nil), "pb.Address")
	proto.RegisterType((*Iface)(nil), "pb.Iface")
	proto.RegisterType((*Machine)(nil), "pb.Machine")
	proto.RegisterType((*SaveMachineReq)(nil), "pb.SaveMachineReq")
	proto.RegisterType((*SaveMachineRes)(nil), "pb.SaveMachineRes")
}

func init() { proto.RegisterFile("workerServer.proto", fileDescriptor_918d5dbb74273f6d) }

var fileDescriptor_918d5dbb74273f6d = []byte{
	// 380 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0x41, 0xef, 0xd2, 0x40,
	0x10, 0xc5, 0x6d, 0xa1, 0x14, 0xa6, 0x40, 0xc8, 0xc4, 0x43, 0xc3, 0xc1, 0xd4, 0x26, 0x26, 0x9c,
	0x6a, 0x82, 0x1a, 0x35, 0xf1, 0x42, 0x90, 0x44, 0x63, 0x2c, 0x64, 0x41, 0xf1, 0x66, 0x96, 0x32,
	0x86, 0x06, 0xcb, 0x96, 0xdd, 0xb6, 0x7e, 0x05, 0x3f, 0xb6, 0xd9, 0x6d, 0x6b, 0x44, 0xf2, 0xbf,
	0xcd, 0xbc, 0x99, 0xdf, 0x7b, 0x93, 0xcd, 0x02, 0xfe, 0x12, 0xf2, 0x4c, 0x72, 0x4b, 0xb2, 0x22,
	0x19, 0xe5, 0x52, 0x14, 0x02, 0xed, 0xfc, 0x30, 0x1d, 0x26, 0x22, 0xcb, 0xc4, 0xa5, 0x56, 0xc2,
	0x97, 0xd0, 0xdd, 0x08, 0x59, 0x20, 0x42, 0x37, 0x17, 0xb2, 0xf0, 0xad, 0xc0, 0x9a, 0x8d, 0x98,
	0xa9, 0xd1, 0x07, 0x57, 0x91, 0xac, 0xd2, 0x84, 0x7c, 0x3b, 0xb0, 0x66, 0x03, 0xd6, 0xb6, 0xe1,
	0x5b, 0x70, 0x17, 0xc7, 0xa3, 0x24, 0xa5, 0x70, 0x0c, 0x76, 0x9a, 0x1b, 0x6c, 0xc0, 0xec, 0x34,
	0xc7, 0x27, 0xe0, 0x68, 0x58, 0xf9, 0x76, 0xd0, 0x99, 0x79, 0xf3, 0x7e, 0x94, 0x1f, 0x22, 0x9d,
	0xc0, 0x6a, 0x39, 0xfc, 0x06, 0xce, 0xc7, 0x1f, 0x3c, 0x21, 0x9d, 0x78, 0xe1, 0x19, 0x35, 0xa8,
	0xa9, 0xf1, 0x19, 0xb8, 0xbc, 0xf6, 0x6d, 0x70, 0x4f, 0xe3, 0x4d, 0x14, 0x6b, 0x67, 0xf8, 0x18,
	0x1c, 0x92, 0x52, 0x48, 0xbf, 0x63, 0xd8, 0xba, 0x09, 0xbf, 0x82, 0xfb, 0x99, 0x27, 0xa7, 0xf4,
	0x62, 0xbc, 0xcb, 0x32, 0x3d, 0xb6, 0xde, 0xba, 0xc6, 0xa7, 0xd0, 0x4b, 0x75, 0x70, 0x6b, 0x3d,
	0xd0, 0xd6, 0xe6, 0x14, 0xd6, 0x0c, 0x1e, 0xf0, 0x7d, 0x0d, 0xe3, 0x2d, 0xaf, 0xa8, 0xf1, 0x66,
	0x74, 0xd5, 0x67, 0x66, 0x75, 0x67, 0x12, 0x9a, 0x33, 0xdb, 0x85, 0x76, 0x16, 0xfe, 0xb6, 0xfe,
	0x23, 0x15, 0xbe, 0x81, 0x9e, 0x2a, 0x78, 0x51, 0x2a, 0x03, 0x8e, 0xe7, 0x81, 0x06, 0x6f, 0x77,
	0x22, 0x46, 0xd7, 0x92, 0x54, 0xb1, 0x35, 0x7b, 0xac, 0xd9, 0x0f, 0xdf, 0xc1, 0xe8, 0x66, 0x80,
	0x1e, 0xb8, 0x5f, 0xe2, 0x4f, 0xf1, 0x7a, 0x1f, 0x4f, 0x1e, 0xe1, 0x10, 0xfa, 0x8b, 0xe5, 0x72,
	0xb5, 0xd9, 0xad, 0xde, 0x4f, 0x2c, 0x9c, 0xc0, 0x30, 0x5e, 0xef, 0xbe, 0xff, 0x55, 0xec, 0x79,
	0x09, 0xde, 0xbe, 0xfe, 0x0e, 0xbc, 0x22, 0x89, 0xcf, 0xc1, 0x59, 0x9e, 0x28, 0x39, 0x23, 0xea,
	0xfc, 0x0f, 0xc4, 0x7f, 0x16, 0x27, 0x23, 0x30, 0xba, 0x4e, 0xef, 0x35, 0x85, 0xaf, 0xc0, 0xfb,
	0xe7, 0xca, 0x1a, 0xbb, 0x7d, 0x94, 0xe9, 0xbd, 0xa6, 0x0e, 0x3d, 0xf3, 0xc9, 0x5e, 0xfc, 0x09,
	0x00, 0x00, 0xff, 0xff, 0xc5, 0xd4, 0x2d, 0xcf, 0x8c, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// WorkerSaverClient is the client API for WorkerSaver service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WorkerSaverClient interface {
	Check(ctx context.Context, in *HealthCheckReq, opts ...grpc.CallOption) (*HealthCheckRes, error)
	SaveMachine(ctx context.Context, in *SaveMachineReq, opts ...grpc.CallOption) (*SaveMachineRes, error)
}

type workerSaverClient struct {
	cc *grpc.ClientConn
}

func NewWorkerSaverClient(cc *grpc.ClientConn) WorkerSaverClient {
	return &workerSaverClient{cc}
}

func (c *workerSaverClient) Check(ctx context.Context, in *HealthCheckReq, opts ...grpc.CallOption) (*HealthCheckRes, error) {
	out := new(HealthCheckRes)
	err := c.cc.Invoke(ctx, "/pb.WorkerSaver/Check", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerSaverClient) SaveMachine(ctx context.Context, in *SaveMachineReq, opts ...grpc.CallOption) (*SaveMachineRes, error) {
	out := new(SaveMachineRes)
	err := c.cc.Invoke(ctx, "/pb.WorkerSaver/SaveMachine", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorkerSaverServer is the server API for WorkerSaver service.
type WorkerSaverServer interface {
	Check(context.Context, *HealthCheckReq) (*HealthCheckRes, error)
	SaveMachine(context.Context, *SaveMachineReq) (*SaveMachineRes, error)
}

// UnimplementedWorkerSaverServer can be embedded to have forward compatible implementations.
type UnimplementedWorkerSaverServer struct {
}

func (*UnimplementedWorkerSaverServer) Check(ctx context.Context, req *HealthCheckReq) (*HealthCheckRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Check not implemented")
}
func (*UnimplementedWorkerSaverServer) SaveMachine(ctx context.Context, req *SaveMachineReq) (*SaveMachineRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveMachine not implemented")
}

func RegisterWorkerSaverServer(s *grpc.Server, srv WorkerSaverServer) {
	s.RegisterService(&_WorkerSaver_serviceDesc, srv)
}

func _WorkerSaver_Check_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerSaverServer).Check(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.WorkerSaver/Check",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerSaverServer).Check(ctx, req.(*HealthCheckReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerSaver_SaveMachine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveMachineReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerSaverServer).SaveMachine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.WorkerSaver/SaveMachine",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerSaverServer).SaveMachine(ctx, req.(*SaveMachineReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _WorkerSaver_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.WorkerSaver",
	HandlerType: (*WorkerSaverServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Check",
			Handler:    _WorkerSaver_Check_Handler,
		},
		{
			MethodName: "SaveMachine",
			Handler:    _WorkerSaver_SaveMachine_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "workerServer.proto",
}
